baseURL = "https://www.zcj.io"
languageCode = "en-us"
title = "Chaojie Zhu"
theme = "hugo-bearblog-neo"
copyright = "Chaojie Zhu"                 # cactus will use title if copyright is not set
googleAnalytics = "UA-126234988-2"
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
blog = "/p/:slug"
tags = "/blog/:slug"

[markup]
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "dracula"
tabWidth = 4

[params]
title = "Chaojie Zhu"
# Home page settings
description = """
  ğŸ‘‹ Hello there, I'm Chaojie Zhu, currently a software engineer at Apple. Welcome to by blog.
  """
favicon = "images/favicon.ico"
dateFormat = "2006-01-02"
copyright = "Copyright Â© 2021-2025, Chaojie Zhu."
groupByYear = true
showPostCount = true
postSearch = true
toc = true
upvote = false

[params.footer]
# æ˜¯å¦éšè—ç‰ˆæƒè¯´æ˜æ–‡æ¡ˆï¼Œè‹¥ä¸é…ç½®ï¼Œé»˜è®¤ false
# Whether to hide the copyright notice text, if not configured, the default is false.
hideCopyright = false
# æ˜¯å¦éšè— Sitemap é“¾æ¥ï¼Œä¸éšè—æœ‰åˆ©äº SEOï¼Œè‹¥ä¸é…ç½®ï¼Œé»˜è®¤ false
# Whether to hide the Sitemap link, not hiding is beneficial for SEO, if not configured, the default is false.
hideSitemap = false
# æ˜¯å¦éšè— made-with-lineï¼Œè‹¥ä¸é…ç½®ï¼Œé»˜è®¤ falseï¼Œä½ å¯ä»¥å…³é—­å®ƒï¼Œä½†å¦‚æœä½ ä¸è¿™æ ·åšï¼Œæˆ‘å°†éå¸¸æ„Ÿæ¿€ :-)
# Whether to hide made-with-line, if not configured, the default is false, you can turn it off, but if you don't, I will be very grateful :-)
hideMadeWithLine = false
# æ˜¯å¦éšè— RSS å’Œ Email é“¾æ¥ï¼Œè‹¥ä¸é…ç½®ï¼Œé»˜è®¤ false
# Whether to hide RSS and Email links, if not configured, the default is false.
hideRSSAndEmail = false

[params.RSS]
# æ˜¯å¦å¯ç”¨ RSSï¼Œè‹¥ä¸é…ç½®ï¼Œé»˜è®¤ true
# Is RSS enabled? If not configured, the default is true.
enableRSS = true
# ç”Ÿæˆçš„ RSS æ–‡ä»¶ä¸­æ–‡ç« æ•°é‡é™åˆ¶ï¼Œè‹¥ä¸é…ç½®ï¼Œå³ä¸è®¾é™åˆ¶
# The article quantity limit in the generated RSS file, if not configured, no limit is set.
pageLimit = 10

[params.author]
# è‹¥ä¸é…ç½®ï¼Œé»˜è®¤ç©º
# If not configured, default is empty
name = "Chaojie Zhu"
# è‹¥ä¸é…ç½®ï¼Œé»˜è®¤ç©º
# If not configured, default is empty
email = "me@zcj.io"
